In [1]:
import torch
import numpy as np

예제 3.1 - 텐서 생성

In [2]:
print(torch.tensor([1,2,3]))
print(torch.Tensor([[1,2,3],[4,5,6]]))
print(torch.LongTensor([1,2,3]))
print(torch.FloatTensor([1,2,3]))

tensor([1, 2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([1, 2, 3])
tensor([1., 2., 3.])


예제 3.2 - 텐서 속성

In [3]:
tensor = torch.rand(1,2)
print(tensor)
print(tensor.shape, tensor.dtype, tensor.device)

tensor([[0.1803, 0.1807]])
torch.Size([1, 2]) torch.float32 cpu


예제 3.3 - 텐서 차원 변환

In [4]:
tensor = torch.rand(1,2)
print(tensor)
print(tensor.shape)

tensor = tensor.reshape(2,1)
print(tensor)
print(tensor.shape)

tensor([[0.0066, 0.6362]])
torch.Size([1, 2])
tensor([[0.0066],
        [0.6362]])
torch.Size([2, 1])


예제 3.4 - 텐서 자료형 설정

In [5]:
tensor = torch.rand((3,3), dtype=torch.float)
print(tensor)

tensor([[0.9592, 0.4389, 0.4563],
        [0.8738, 0.8092, 0.1041],
        [0.0986, 0.4870, 0.9785]])


예제 3.5 - 텐서 GPU 장치 설정

In [6]:
device = "cuda" if torch.cuda.is_available() else "cpu"
cpu = torch.FloatTensor([1,2,3])
# gpu = torch.cuda.FloatTensor([1,2,3])   # old notation. use below one.
gpu = torch.tensor([1,2,3], dtype=torch.float, device='cuda')   # this one!
tensor = torch.rand((1,1), device=device)
print(device)
print(cpu)
print(gpu)
print(tensor)

cuda
tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')
tensor([[0.4409]], device='cuda:0')


예제 3.6 - 텐서 장치 변환

In [7]:
cpu = torch.FloatTensor([1,2,3])
gpu = cpu.cuda()
gpu2cpu = gpu.cpu()
cpu2gpu = cpu.to('cuda')
print(cpu)
print(gpu)
print(gpu2cpu)
print(cpu2gpu)

tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')
tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')


예제 3.7 - 넘파이 배열의 텐서 변환

In [8]:
ndarray = np.array([1,2,3], dtype=np.uint8)
print(torch.tensor(ndarray))
print(torch.Tensor(ndarray))
print(torch.from_numpy(ndarray))

tensor([1, 2, 3], dtype=torch.uint8)
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.uint8)


예제 3.8 - 텐서의 넘파이 배열 변환

In [10]:
tensor = torch.tensor([1,2,3], dtype=torch.float, device='cuda')
ndarray = tensor.detach().cpu().numpy()
print(ndarray)
print(type(ndarray))

[1. 2. 3.]
<class 'numpy.ndarray'>


✔ 오늘 새로 알게된 부분이 있다면 간략히 설명해주세요.

- `torch.tensor()` 보다는 `torch.Tensor()`를 사용하는 게 낫다.
- 텐서는 `shape`, `dtype`, `device`가 모두 일치해야 서로 연산할 수 있다. 이 중 device는 `.cpu()` 나 `.cuda()` 를 통해서 하면 된다.
- 텐서는 학습을 위한 데이터 형식으로, 모든 연산을 추적해 기록한다. 이 기록을 통해 역전파 등과 같은 연산이 진행되어 모델 학습이 이루어진다. 다시 말해, 텐서의 데이터가 어떻게 변경되고 관리되었는지 기록된다.
- 연속형 변수에 사용되는 loss function에는 [squared error, sum of squared error, mean squared error] 등이 있고, 이산형 변수에 사용되는 loss function에는 [cross entropy] 등이 있다. cross entropy는 실제값의 확률분포와 예측값의 확률분포 간의 차이를 계산한다. { - sum ( y * log (y_hat) )} 꼴이다.
- 최적화 알고리즘에는 [gradient descent (GD), momentum, adaptive gradient (AdaGrad), Adaptive Moment Estimation (Adam)] 등이 있다.